version: '3.9'

services:
  migrate:
    image: migrate/migrate
    networks:
      - ntwork
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:${POSTGRES_PASSWORD}@postgres2:5432/ecommerce_auth_service?sslmode=disable", "up"]
    depends_on:
      - postgres
    
  postgres:
    image: postgres:16.3
    container_name: postgres2
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ecommerce_auth_service
    networks:
      - ntwork
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres2"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres-data:/ecommerce-auth/postgresql/data
    
  auth:
    container_name: ecommerce-auth
    build: .
    depends_on:
      - postgres
    networks:
      - ntwork
    ports:
      - "8081:8081"

networks:
  ntwork:
    external: true
    name: onenet

volumes:
  postgres-data:
